version: '3'

services:

  mysql_db:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: deribit_db
      MYSQL_ROOT_HOST: '%'
    container_name: database
    restart: always
    ports:
      - 3310:3306
    expose:
      - 3306
    volumes:
      - ./db_deribit:/var/lib/mysql

  python_app:
    build: .
    container_name: deribit_app
    ports:
    - 80:80
    working_dir: /app/deribit
    command: python main.py
    depends_on:
      - mysql_db