version: '3'

services:
  mysql_db:
    image: mysql:8.0.26
    restart: always
    container_name: database
    ports:
      - 3310:3306
    expose:
      - 3306
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: deribit_db
    volumes:
      - ./db_deribit:/var/lib/mysql

  python_app:
    build: .
    image: deribit:app
    container_name: deribit_app
    ports:
    - 80:80
    working_dir: /app/deribit
    command: ["../wait-for-it.sh", "database:3306", "--", "python", "main.py"]
    depends_on:
      - mysql_db
    volumes:
    - ./deribit/settings.json:/var/deribit/settings.json

volumes:
  db_deribit: