version: '3'

services:

  mysql_db:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: deribit_db
      MYSQL_USER: babaska
      MYSQL_PASSWORD: Cfdjhbyf33
    container_name: database
    ports:
      - 3310:3306
    expose:
      - 3306
 #   networks:
 #     - my_net
    volumes:
      - ./db_deribit:/var/lib/mysql

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
 #   networks:
 #     - my_net
    ports:
    - 80:80
    depends_on:
      - mysql_db
    command:
      python ./deribit/main.py

#networks:
# my_net:
#    driver: bridge